# Generated by Django 5.2 on 2026-10-09 19:11

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('resource_type', models.CharField(blank=True, max_length=60)),
                ('resource_id', models.CharField(blank=True, max_length=120)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('failed', 'Failed'), ('info', 'Info')], db_index=True, default='info', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Original display name shown to users.', max_length=255)),
                ('stored_file', models.FileField(upload_to=core.models._document_upload_path)),
                ('doc_type', models.CharField(choices=[('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('imaging', 'Imaging / Radiology'), ('discharge', 'Discharge Summary'), ('referral', 'Referral Letter'), ('other', 'Other')], default='other', max_length=30)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.patientprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SharingGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_grants', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.medicaldocument')),
                ('otp_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharing_grant', to='core.otptoken')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharing Grant',
                'ordering': ['-created_at'],
            },
        ),
    ]
